# Generated by Django 2.1.3 on 2018-11-24 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipient_account',
            field=models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='Niewłaściwy numer konta - za mało cyfr', regex='[0-9]{26}')]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_name',
            field=models.CharField(max_length=80),
        ),
    ]
